# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Dotnet Restore
  inputs:
    command: 'restore'
    projects: 'GameOfLifeAPI.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './GameOfLifeAPI.sln'
    arguments: '-c Release --no-restore --no-build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './src/GameOfLifeKata.API/GameOfLife.Kata.API.csproj'
    arguments: '-c Release -o $(build.artifactstagingdirectory)//out --no-restore --no-build'
- task: PublishBuildArtifacts@1
  displayName: 'Resulted published'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
